# Generated by Django 5.0.7 on 2024-07-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_search_country_search_latitude_search_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='country',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='longitude',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
