# Generated by Django 5.0.7 on 2024-07-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_search_country_alter_search_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='latitude',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
