# Generated by Django 5.0.7 on 2024-07-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_search_country_alter_search_latitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=200, null=True)),
                ('remaining_days', models.IntegerField(blank=True, editable=False, null=True)),
                ('link', models.URLField(blank=True, null=True, verbose_name='Google Form Link')),
            ],
            options={
                'verbose_name': 'Event Detail',
                'verbose_name_plural': 'Event Details',
            },
        ),
    ]
